<a href="https://colab.research.google.com/github/markzaldivar/MAT422/blob/main/LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra
Linear algebra is a branch of mathematics concerning vector spaces, matrices, and linear transformations. It has various applications in a wide range of fields and many such applications can be facilitated through Python packages.


In [ ]:
import numpy as np
import sympy
import scipy.linalg as la
import math

# 1.2.1 Linear Spaces

We begin with some definitions. A linear combination is a vector constructed from a subset by multiplying each vector by a constant and adding the results. A linear subspace is a subset of all linear combinations.

Let $ \mathbf{w}_1, \dots, \mathbf{w}_m \in V $. The span of $ \{\mathbf{w}_1, \dots, \mathbf{w}_m\} $, denoted $\text{span}(\mathbf{w}_1, \dots, \mathbf{w}_m)$, is the set of all linear combinations of the $\mathbf{w}_j$'s. That is,

$$
\text{span}(\mathbf{w}_1, \dots, \mathbf{w}_m) = \left\{ \sum_{j=1}^{m} \alpha_j \mathbf{w}_j : \alpha_1, \dots, \alpha_m \in \mathbb{R} \right\}.
$$

A list of vectors are linearly independent if they cannot be written as a linear combination of the others.

A basis is a set of vectors that generates all elements of the vector space and the vectors in the set are linearly independent.

Below we determine if a set of vectors are linearly independent by solving the matrix equation

$$ A\mathbf{x} = 0\$$

If the only solution is the trivial solution, $\mathbf{x}=0$, we conclude that the vectors that comprise the columns of matrix $\mathbf{A}$ are linearly independent


In [ ]:

A = np.array([[1,-1,2,0],[1,1,5,0],[3,-1,6,0],[3,-3,9,0]])
rref=sympy.Matrix(A).rref()
print(A)
print(rref)
print("The vectors are linearly independent")

[[ 1 -1  2  0]
 [ 1  1  5  0]
 [ 3 -1  6  0]
 [ 3 -3  9  0]]
(Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 0]]), (0, 1, 2))
The vectors are independent


# 1.2.2 Orthogonality
A list of vectors $\{ \mathbf{u}_1, \dots, \mathbf{u}_m \}$ is *orthonormal* if the $\mathbf{u}_i$'s are pairwise orthogonal and each has norm 1, that is, for all $i$ and $j \neq i$,

$$
\langle \mathbf{u}_i, \mathbf{u}_j \rangle = 0,
$$

and

$$
\|\mathbf{u}_i\| = 1.
$$
where the inner product is

$$
\langle \mathbf{u}, \mathbf{v} \rangle = \mathbf{u} \cdot \mathbf{v} = \sum_{i=1}^{n} u_i v_i
$$

and the norm is

$$
\| \mathbf{u} \| = \sqrt{\sum_{i=1}^{n} u_i^2}
$$


The use of orthonormal bases can greatly simplify porblems in many applications. Below we compute several inner products and norms:



In [ ]:


u1 = np.array([1,2,3])
u2 = np.array([3,4,5])
print("Inner Product equals" , u1@u2)
print("Norm of u1 equals" , np.linalg.norm(u1))
print("Norm of u2 equals" , np.linalg.norm(u2))

Inner Product equals 26
Norm of u1 equals 3.7416573867739413
Norm of u2 equals 7.0710678118654755


Next we verify if a set of vectors is orthonormal

In [ ]:


u1 = np.array([1/math.sqrt(2),-1/math.sqrt(2),0])
u2 = np.array([1/math.sqrt(2),1/math.sqrt(2),0])
print(u1@u2) #Inner Product
print(np.linalg.norm(u1)) #Norm of u1
print(np.linalg.norm(u2)) #Norm of u2
print("The vectors are orthornormal")


0.0
0.9999999999999999
0.9999999999999999
The vectors are orthornormal


# 1.2.3 Gram-Schmidt Process
The Gram-Schmidt Process is an algorithm used to obtain an orthonormal basis from a linearly independent set of vectors. The algorithm takes advantage of orthogonal porjection while ensuring that the vectors span the same space. Below is the algorithm implemented in Python:

In [ ]:


def gram_schmidt(vectors):

    orthonormal_basis = []

    for v in vectors:
        # original vector
        orthogonal_v = v

        # Subtract projections onto previously computed basis vectors
        for basis_vector in orthonormal_basis:
            projection = np.dot(v, basis_vector) * basis_vector
            orthogonal_v = orthogonal_v - projection

        # Normalize orthogonalized vector
        norm = np.linalg.norm(orthogonal_v)
        orthonormal_v = orthogonal_v / norm


        orthonormal_basis.append(orthonormal_v)

    return orthonormal_basis


vectors = [np.array([2, 1, 0]), np.array([1, 0, 1]), np.array([0, 1, 3])]
orthonormal_basis = gram_schmidt(vectors)


for i, vec in enumerate(orthonormal_basis):
    print(f"Orthonormal vector {i+1}: {vec}")


Orthonormal vector 1: [0.89442719 0.4472136  0.        ]
Orthonormal vector 2: [ 0.18257419 -0.36514837  0.91287093]
Orthonormal vector 3: [-0.40824829  0.81649658  0.40824829]


# 1.2.4 Eigenvalues and Eigenvectors
For a square matrix $A$, the eigenvalue λ is given by the following equation:
$$A\mathbf{x}=λ\mathbf{x}$$
where $\mathbf{x}$ is the corresponding non-zero eigenvector.

Eigenvalues and eigenvectors appear in various applications. One especially useful application is the diagonalization of matrices, which is demonstrated below:


In [27]:

A = sympy.Matrix([[-1, -2,  2],
            [4,  3, -4],
            [0, -2,  1],
            ])

print("Matrix : {} ".format(A))

# Use sympy.diagonalize() method
P, D = A.diagonalize()

print("Diagonal of a matrix : {}".format(D))

Matrix : Matrix([[-1, -2, 2], [4, 3, -4], [0, -2, 1]]) 
Diagonal of a matrix : Matrix([[-1, 0, 0], [0, 1, 0], [0, 0, 3]])
